---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-docker-getting-started
spec:
  type: LoadBalancer
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    com.docker.project: kubernetes-docker-getting-started
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-docker-getting-started
  labels:
    com.docker.project: kubernetes-docker-getting-started
spec:
  replicas: 1
  selector:
    matchLabels:
      com.docker.project: kubernetes-docker-getting-started
  template:
    metadata:
      labels:
        com.docker.project: kubernetes-docker-getting-started
    spec:
      containers:
        - name: kubernetes-docker-getting-started
          image: docker/getting-started
          ports:
          - containerPort: 80
            protocol: TCP
      restartPolicy: Always
