# https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-config-file/#create-the-config-file
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: app-mongo
type: Opaque
data:
  mongodb-root-username: dXNlcm5hbWU=
  mongodb-root-password: cGFzc3dvcmQ=
