# https://kubernetes.io/docs/concepts/configuration/configmap/#configmaps-and-pods
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: app-mongo
data:
  mongodb-url: mongodb-service
