# https://kubernetes.io/docs/tasks/administer-cluster/namespaces/#creating-a-new-namespace
apiVersion: v1
kind: Namespace
metadata:
  name: app-mongo
---
# https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-config-file/#create-the-config-file
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: app-mongo
type: Opaque
data:
  mongodb-root-username: dXNlcm5hbWU=
  mongodb-root-password: cGFzc3dvcmQ=
---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: app-mongo
  labels:
    app: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo # https://hub.docker.com/_/mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME # Environment Variables
          valueFrom:
            secretKeyRef: # https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
              name: mongodb-secret
              key: mongodb-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD # Environment Variables
          valueFrom:
            secretKeyRef: # https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
              name: mongodb-secret
              key: mongodb-root-password
---
# https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: app-mongo
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017 # Mongodb port
      targetPort: 27017 # Mongodb port
---
# https://kubernetes.io/docs/concepts/configuration/configmap/#configmaps-and-pods
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: app-mongo
data:
  mongodb-url: mongodb-service
---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress-deployment
  namespace: app-mongo
  labels:
    app: mongoexpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
      - name: mongoexpress
        image: mongo-express # https://hub.docker.com/_/mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME # Configuration
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD # Configuration
          valueFrom:
            secretKeyRef: # https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
              name: mongodb-secret
              key: mongodb-root-password
        - name: ME_CONFIG_MONGODB_SERVER # Configuration
          valueFrom:
            configMapKeyRef: # https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
              name: mongodb-configmap
              key: mongodb-url
---
# https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors
apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-service
  namespace: app-mongo
spec:
  selector:
    app: mongoexpress
  ports:
    - protocol: TCP
      port: 8081 # mongoexpress port
      targetPort: 8081 # mongoexpress port
---
# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongoexpress-ingress
  namespace: app-mongo
spec:
  rules:
  - host: "mongoexpress.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mongoexpress-service
            port:
              number: 8081
